version: '3.3'

networks:
  default:
    name: recovery-assistant-localstack

volumes:
  localstack:

services:
  localstack:
    container_name: recovery-assistant-localstack
    image: localstack/localstack:latest
    ports:
      - 8080:8080
      - 4566:4566
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - PORT_WEB_UI=8080
    volumes:
      - ${PWD}/.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: dbUser
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: thisispwd
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/